name: Lint & test

on: 
  push:
    branches:
      - '*'


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade-pip
          pip install -r requirements-dev.txt
      
      - name: black
        run: python -m black --check --line-length 120 fancy_signatures

      - name: mypy
        run: python -m mypy fancy_signatures --ignore-missing-imports

      - name: test
        run: python -m pytest fancy_signatures/tests