name: Lint & test

on: 
  push:
    branches:
      - '*'


jobs:
  validate-and-test:
    name: Run linters & tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      
      - name: black
        run: black --check --line-length 120 fancy_signatures

      - name: mypy
        run: mypy fancy_signatures --ignore-missing-imports

      - name: test
        run: pytest tests